### ISSUE TITLE
Delete GPX route

### ISSUE THREAD

**Issue by Rasbats** [opencpn-finSAR/finSAR_edit_pi#1]
With this plugin we are working with RTZ format files iso GPX.

I want to use OpenCPN to make the route but after saving as RTZ, delete the route. Usually if you delete the waypoints the route disappears.

@TwoCanPlugin ;The super-gurus are busy with 5.9.x. Could you take a look?

[https://github.com/opencpn-finSAR/finSAR_edit_pi/blob/main/src/finSAR_editUIDialog.cpp](https://github.com/opencpn-finSAR/finSAR_edit_pi/blob/main/src/finSAR_editUIDialog.cpp)

Around line 845 is where I am trying to delete a unique_ptr.

**Comment by TwoCanPlugIn** [comment]
Hi Mike,

Not sure what the problem is nor exactly what I'm looking for. Unless I'm missing something obvious, your question may be beyond my pay grade.

If you're trying to delete a route, wouldn't DeletePlugInRoute do the trick?

I've never tried to delete a route by deleting it's constituent waypoints. Wouldn't that just leave an empty route? And I'm unsure if it's even possible to do that, at least from what I can tell, in the UI you can't edit the properties of a route and remove all the waypoints. It needs a start and end. I've no idea whether there is any underlying mechanism in OpenCPN that preserves the referential integrity of a route (ie. it must have a start and an end).

Wrt to the managed pointers, e.g. std::vector<std::unique_ptr<PlugIn_Route_Ex>> routes;

Ordinarily once the ptr goes out of scope it is automagically cleaned up.

However with your vector of ptr's once you've deleted the route, you'll need to keep your vector in synch by, I'm guessing, either by calling the ptr's reset method or simply deleting the entry. You could set it to nullptr but that will mean the size of the vector does not accurately reflect the number of routes..

Is this pseudo code what you're trying to achieve ?

std::vector<std::unique_ptr<PlugIn_Route_Ex>> routes;
// Get routes from OpenCPN
....
GetRouteGuidArray()
routes.push_back(.....);
...
// Populate the list control
for  (auto it : routes) {
 routeListControl.InsertItem(it.m_NameString)
}
....
//pick a route to export then subsequently delete

index = routeListControl.GetNextItem....
....
Plugin_Route_Ex routeToDelete =routes.at(index);
...
// delete route from opencpn
DeletePlugInRoute(routeToDelete.m_GUID);
....
// keep the vector in synch
routes.at(index).reset(); or routes.erase(index)
....
// Update the list control
routeList.Delete(index);

 If this is not what you're looking, I'm not sure I can add anything else.

Regards,

Steven.

________________________________
From: Rasbats ***@***.***>
Sent: 07 July 2024 16:49
To: opencpn-finSAR/finSAR_edit_pi ***@***.***>
Cc: TwoCanPlugIn ***@***.***>; Mention ***@***.***>
Subject: [opencpn-finSAR/finSAR_edit_pi] Delete GPX route (Issue #1)


With this plugin we are working with RTZ format files iso GPX.

I want to use OpenCPN to make the route but after saving as RTZ, delete the route. Usually if you delete the waypoints the route disappears.

@TwoCanPlugIn<https://github.com/TwoCanPlugIn> ;The super-gurus are busy with 5.9.x. Could you take a look?

https://github.com/opencpn-finSAR/finSAR_edit_pi/blob/main/src/finSAR_editUIDialog.cpp

Around line 845 is where I am trying to delete a unique_ptr.

**Comment by Rasbats** [comment]
"delete the route"
Thanks Steve ...   `DeletePlugInRoute` did the business. How did I miss that?

**Comment by TwoCanPlugIn** [comment]
> How did I miss that?

Didn't read the developer documentation?

Oops, forgot, there isn't any!

Cheers....

**Comment by Rasbats** [comment]
Now working ok.

**Comment by Rasbats** [comment]
Closing
